### ISSUE TITLE
Sync button

### ISSUE THREAD

**Issue by larsgson** [unfoldingWord/gateway-translate#136] opened 2023-02-01 10:20 UTC
From meetings in Orlando last week we found that there is a need for the various uW apps to have a sync button - meaning to make it easy to merge the main branch into the currently used personal branch.

The sync button can be pressed (show it enabled), when there is no conflict.
If there is a conflict, then maybe this button can show up as red (and disabled).

From @richmahn I have this information:
- if a pull request results in a conflict, then a flag, as received from an API call, indicates if the text is mergeable or not.
- Here is an example :
https://git.door43.org/api/v1/repos/unfoldingWord/en_tn/pulls/3114
- indicating "mergeable" as false

**Comment by birchamp** [comment] 2023-10-17 14:54
This is a dupe of the merge epic #183

**Closed by birchamp** 2023-10-17 14:54 UTC
Labels: duplicate
